### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by abibouba** [timhaak/docker-plexpass#1]
Hi Timhaak,

Can you update the media server to latest version (0.9.12.10)?

The current version in your docker image (0.9.12.4) doesn't work with the brand new iOS app.

**Comment by timhaak** [comment]
Hi

I've just triggered a rebuild. 

This is normally done once a day automatically. 

Its also dependent on the new version being available from the ppa.

Try do a pull in about half an hour (rebuild should be finished then).

If its still not available give it 24 hours and try again.

**Comment by timhaak** [comment]
Just double checked against the version from plex. Its currently 0.9.12.8.

My plex is at 0.9.12.8.

Have you done a docker pull to update your version, removed the old running container then started it again ?

docker stop plex
docker rm -f plex
docker run -d {your settings here} --name plex  timhaak/plexpass

Going to close as it all seems to be correct.
