### ISSUE TITLE
Important: This registry version will not be supported in future versions of docker

### ISSUE THREAD

**Issue by Bodge-IT** [timhaak/docker-plexpass#2]
Latest pull from Github gets this warning after download:
Important: This registry version will not be supported in future versions of docker

**Comment by timhaak** [comment]
Hi

Which version of docker are you using?

I think that message is telling you that your trying to connect to the version 1 of the registry api.

Docker hub should be supporting both at the moment though they are going to be deprecating the one soon. 

Hence the warning.

**Comment by timhaak** [comment]
I'm going to close this one.

Please reply on the timhaak/docker repo.
