### ISSUE TITLE
can't add it to my lsit of server

### ISSUE THREAD

**Issue by boistordu** [timhaak/docker-plexpass#5]
I have several plex server on my network and I can't link it to my account. If I go to the page, it asks me to auth myself and then I 'ms just linked to my other servers already linked

**Comment by boistordu** [comment]
go look at this issue : https://github.com/timhaak/docker-plex/issues/59 
and make adjustment in a hurry please

**Comment by timhaak** [comment]
Hi replied to your other issue.

Though I find the statement "make adjustment in a hurry please".

This is a side line things for all the people committing and not work or a job.

We do try and fix things when we can but there is no have to.

Please in future take this under consideration and realise that you're asking a favour.
