### ISSUE TITLE
maybe it's better to do update the plex in other ways

### ISSUE THREAD

**Issue by boistordu** [timhaak/docker-plexpass#7]
What if we add after the apt-get update of the plex pass this one :+1: apt-get install -qy dbus avahi-daemon wget && \
curl -L 'https://plex.tv/downloads/latest/1?channel=8&build=linux-ubuntu-x86_64&distro=ubuntu' -o /tmp/plexmediaserver.deb &&

and like that we could be sure to have always the last version even if the apt mirror doesn't respond anymore?

**Comment by timhaak** [comment]
Moving everything to https://github.com/timhaak/docker-plex
